//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_LocomotionTest : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean left_A_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_left_A_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_B_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_left_B_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_A_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_right_A_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_B_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_right_B_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_grip_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_left_grip_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_grip_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_right_grip_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_trigger_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_left_trigger_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_trigger_down
        {
            get
            {
                return SteamVR_Actions.locomotionTest_right_trigger_down;
            }
        }
        
        public virtual SteamVR_Action_Vector2 left_thumb_analog
        {
            get
            {
                return SteamVR_Actions.locomotionTest_left_thumb_analog;
            }
        }
        
        public virtual SteamVR_Action_Vector2 right_thumb_analog
        {
            get
            {
                return SteamVR_Actions.locomotionTest_right_thumb_analog;
            }
        }
    }
}
